# Generated by Django 3.0.11 on 2020-11-21 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animals',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=128, verbose_name='Кличка')),
                ('profile_link', models.URLField(verbose_name='Ссылка на профиль')),
                ('shelter', models.CharField(max_length=255, verbose_name='Название приюта')),
                ('city', models.CharField(max_length=64, verbose_name='Город')),
                ('breed', models.CharField(max_length=128, verbose_name='Порода животного')),
                ('kind', models.CharField(max_length=64, verbose_name='Вид животного')),
                ('birthday', models.DateField(verbose_name='День рождения')),
                ('gender', models.CharField(max_length=10, verbose_name='Пол')),
                ('counter_favorite', models.IntegerField(verbose_name='В избранном')),
                ('counter_home', models.IntegerField(verbose_name='Уже дома')),
                ('counter_take', models.IntegerField(verbose_name='Забрать домой')),
                ('counter_walking', models.IntegerField(verbose_name='Погулять')),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='ID client')),
                ('shelter', models.CharField(max_length=255, verbose_name='Название приюта')),
                ('datetime', models.DateTimeField(verbose_name='Дата-время платежа')),
                ('item', models.CharField(max_length=255, verbose_name='Наименование услуги')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма платежа')),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название операции')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма операции')),
                ('datetime', models.DateTimeField(verbose_name='Дата')),
                ('order_id', models.IntegerField(verbose_name='Номер заказа')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='api.Animals')),
            ],
        ),
    ]
